# Create class
POST http://localhost:3333/classes 
content-type: application/json

{
    "name": "Filipe Simon",
    "avatar": "https://avatars1.githubusercontent.com/u/67447916?s=460&u=11b173b9d0b23c96adad5c050a57bb2437fc752f&v=4",
    "whatsapp": "13974207073",
    "bio": "Entusiasta das melhores tecnologias de química avançada. Apaixonado por explodir coisas em laboratório e por mudar a vida das pessoas através de experiências. Mais de 200.000 pessoas já passaram por uma das minhas explosões.", 
    "subject": "Química",
    "cost": 80,
    "schedule": [
        { "week_day": 1, "from": "8:00", "to": "12:00" },
        { "week_day": 3, "from": "10:00", "to": "18:00" },
        { "week_day": 5, "from": "08:00", "to": "12:00" }
    ]
}

###

# List classes
GET http://localhost:3333/classes
    ?week_day=4
    &subject=Geografia
    &time=11:00

###

# Create conjnections
POST http://localhost:3333/connections
content-type: application/json

{
    "user_id": 1
}

###

# List connections
GET http://localhost:3333/connections